package hamcrest;

/* AllTests - generated by Ian Darwin's alltest script */

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(value=Suite.class)
@SuiteClasses(value={
	AssumptionDemo.class,
	HamcrestDemo.class,
	TheoriesDemo.class,
})
public class AllTests {
	// No Code Needed
}

