package xml;

/* AllTests - generated by Ian Darwin's alltest script */

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(value = Suite.class)
@SuiteClasses(value = { 
		TestDocumentsEqual.class,
		// TestDocumentsEqualDetailed.class, // Omit - expected to fail
		TestXMLValidityWithSchema.class,
		TestXMLWellFormed.class, 
		TestXPathWithXMLUnit.class, 
		TestXPathWithoutXMLUnit.class,
		TestXSLTwithXPath.class,
})
public class AllTests {
	// No Code Needed
}
