package common;

/* AllTests - generated by Ian Darwin's alltest script */

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(value=Suite.class)
@SuiteClasses(value={
	IntegerCompareTest.class,
	StringUpperCaseTest.class,
	StringUpperCaseTest2.class,
	TestCalendarGetInstance.class,
	TestCalendarSettersGetters.class,
	TestCardData.class,
	//TestCardValidator.class,
	TestCardValidatorByEnum.class,
	TestConstructor.class,
	TestEquals1.class,
	TestEqualsWithEqualsTester.class,
	TestShouldThrow.class,
	TestVISACardValidator.class,
	WasteOfTime.class,
})
public class AllTests {
	// No Code Needed
}

